services:
  be:
    image: ${BE_IMAGE:-quanlyhosoan-be:latest}
    container_name: quanlyhosoan_be
    restart: unless-stopped
    environment:
      - PORT=${PORT:-8001}
    ports:
      - "${PORT:-8001}:8001"
    volumes:
      - ./db_data:/app/data
      - ./uploads:/app/backend/uploads
  fe:
    image: ${FE_IMAGE:-quanlyhosoan-fe:latest}
    container_name: quanlyhosoan_fe
    restart: unless-stopped
    depends_on:
      - be
    ports:
      - "${FRONTEND_PORT:-3000}:3000"

volumes:
  db_data:
